parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: raha_stage
    database_user: root
    database_password: toor
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 6ee1931501454d20e5b9a2a2973ac858dd794dcd
    database_path: null
