parameters:
#    raha_admin.example.class: Raha\AdminBundle\Example

services:
#    raha_admin.example:
#        class: %raha_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
