parameters:
#    raha_home.example.class: Raha\HomeBundle\Example

services:
#    raha_home.example:
#        class: %raha_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
